spring.application.name=restaurante


spring.datasource.url=jdbc:h2:mem:restaurantebd

spring.datasource.driverClassName=org.h2.Driver
spring.datasouce.username=sa
spring.datasouce.password=


spring.h2.console.enable=true
spring.h2.console.path=/h2-console


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
